# Server configuration
server:
  port: 8080

spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/customers
    username: root
    password: rootuser
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false

  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret:
    key: J1pUaSLrDyiUeMfKMHsNLkRKtkSxrV167mCeGmigTwc=
  expiry:
    time: 86400000
